# NetFlux5G - gNB (Next Generation NodeB) Configuration
# UERANSIM gNB configuration for NetFlux5G 5G RAN Simulation

# MCC and MNC configuration
mcc: "999"
mnc: "70"

# gNB Identity
nci: 0x000000010 # NR Cell Identity (36-bit)
idLength: 32 # NR gNB ID length in bits [22...32]
tac: 1 # Tracking Area Code

# IP configuration for gNB
linkIp: 0.0.0.0 # gNB's local IP address for Radio Link Simulation (Use 0.0.0.0 to bind to all interfaces)
ngapIp: 0.0.0.0 # gNB's local IP address for N2 Interface (Use 0.0.0.0 to bind to all interfaces)
gtpIp: 0.0.0.0 # gNB's local IP address for N3 Interface (Use 0.0.0.0 to bind to all interfaces)

# List of AMF configurations
amfConfigs:
  - address: amf # AMF IP address or hostname
    port: 38412 # AMF port for NGAP

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1 # Slice/Service Type
    sd: 0x010203 # Slice Differentiator (optional)

# Ignore stream IDs (leave empty if not needed)
ignoreStreamIds: []

# Logging configuration
logger:
  level: warn # Log level: trace, debug, info, warn, error, fatal

# Cell configuration
cellCfgList:
  - cellId: 1
    # Physical parameters
    earfcn: 632640 # NR-ARFCN for downlink
    txPower: 23 # Transmission power in dBm

    # Frame structure
    numerology: 1 # Subcarrier spacing (0=15kHz, 1=30kHz, 2=60kHz)
    bandwidth: 20 # Channel bandwidth in MHz

    # Beam management
    beamforming:
      enabled: false

# RRC configuration
rrc:
  # Maximum number of UE connections
  maxConnections: 16

  # UE capability parameters
  ueCapability:
    supportedBands: [78, 79] # Supported frequency bands

# Security configuration
security:
  integrityAlgorithms: [NIA1, NIA2, NIA3]
  cipheringAlgorithms: [NEA0, NEA1, NEA2, NEA3]
