# NetFlux5G - gNB (Next Generation NodeB) Configuration
# UERANSIM gNB configuration for NetFlux5G 5G RAN Simulation

# MCC and MNC configuration
mcc: "999"
mnc: "70"

# gNB Identity
nci: 0x000000010 # NR Cell Identity (36-bit)
idLength: 32 # NR gNB ID length in bits [22...32]
tac: 1 # Tracking Area Code

# IP configuration for gNB
linkIp: 127.0.0.1 # gNB's local IP address for Radio Link Simulation
ngapIp: 127.0.0.1 # gNB's local IP address for N2 Interface
gtpIp: 127.0.0.1 # gNB's local IP address for N3 Interface

# List of AMF configurations
amfConfigs:
  - address: amf-test # AMF IP address or hostname
    port: 38412 # AMF port for NGAP

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1 # Slice/Service Type
    sd: 0x010203 # Slice Differentiator

# SCTP configuration
ignoreStreamIds: true # Ignore SCTP stream IDs (boolean format)

# Logging configuration
logger:
  level: warn # Log level: trace, debug, info, warn, error, fatal
