# NetFlux5G - AMF (Access and Mobility Management Function) Configuration
# Open5GS AMF configuration for NetFlux5G 5G Core Network Simulation

db_uri: mongodb://mongodb:27017/open5gs

logger:
  level: info

amf:
  sbi:
    - addr: 0.0.0.0
      port: 7778
  sbi_client:
    nrf:
      - uri: http://nrf-test:7777

  ngap:
    - addr: 0.0.0.0
      port: 38412

  metrics:
    - addr: 0.0.0.0
      port: 9090

  guami:
    - plmn_id:
        mcc: 999
        mnc: 70
      amf_id:
        region: 2
        set: 1

  tai:
    - plmn_id:
        mcc: 999
        mnc: 70
      tac: 1

  plmn_support:
    - plmn_id:
        mcc: 999
        mnc: 70
      s_nssai:
        - sst: 1
          sd: 0x010203

  security:
    integrity_order: [NIA2, NIA1, NIA0]
    ciphering_order: [NEA0, NEA1, NEA2]

  network_name:
    full: NetFlux5G Network
    short: NetFlux5G

  amf_name: NetFlux5G-AMF

  # T3502 timer (periodic registration update timer)
  time:
    t3502:
      value: 720 # 12 minutes
    t3512:
      value: 3240 # 54 minutes
