# NetFlux5G - AUSF (Authentication Server Function) Configuration
# Open5GS AUSF configuration for NetFlux5G 5G Core Network Simulation

db_uri: mongodb://mongodb:27017/open5gs

logger:
  level: info

ausf:
  sbi:
    - addr: ausf-test
      port: 7779
  sbi_client:
    nrf:
      - uri: http://nrf-test:7777

  metrics:
    - addr: 0.0.0.0
      port: 9090

  # Authentication parameters
  authentication:
    # SUPI concealment configuration
    supi_concealment:
      enabled: true

    # 5G AKA authentication
    aka:
      enabled: true

    # EAP-AKA' authentication
    eap_aka_prime:
      enabled: true

nrf:
  sbi:
    - addr: nrf-test
      port: 7777
