# NetFlux5G - PCF (Policy Control Function) Configuration
# Open5GS PCF configuration for NetFlux5G 5G Core Network Simulation

db_uri: mongodb://mongodb:27017/open5gs

logger:
  level: info

pcf:
  sbi:
    - addr: 0.0.0.0
      port: 7781

nrf:
  sbi:
    - addr: nrf-test
      port: 7777
