# NetFlux5G - SMF (Session Management Function) Configuration
# Open5GS SMF configuration for NetFlux5G 5G Core Network Simulation

db_uri: mongodb://mongodb:27017/open5gs

logger:
  level: info
  file: /var/log/open5gs/smf.log

smf:
  sbi:
    - addr: 0.0.0.0
      port: 80

  pfcp:
    - addr: 0.0.0.0
      port: 8805

  gtpc:
    - addr: 0.0.0.0

  gtpu:
    - addr: 0.0.0.0

  metrics:
    - addr: 0.0.0.0
      port: 9090

  subnet:
    - addr: 10.45.0.1/16
      dnn: internet

  dns:
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844

  mtu: 1400

  # P-CSCF configuration
  p_cscf:
    - 127.0.0.1

  # UE Pool configuration for N3 interface
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1

  upf:
    - addr: upf
      port: 8805

nrf:
  sbi:
    - addr: nrf
      port: 7777
