# NetFlux5G - UPF (User Plane Function) Configuration
# Open5GS UPF configuration for NetFlux5G 5G Core Network Simulation

logger:
  level: info

upf:
  pfcp:
    server:
      - address: 0.0.0.0
        port: 8805

  gtpu:
    server:
      - address: 0.0.0.0
        port: 2152

  metrics:
    server:
      - address: 0.0.0.0
        port: 9090

  subnet:
    - addr: 10.45.0.1/16
      dnn: internet
      dev: ogstun
    - addr: 192.168.0.1/24
      dnn: internet2
      dev: ogstun2

  # Enable NAT for internet access
  dev: ogstun

  # MTU configuration
  mtu: 1400

# SMF configuration for UPF
smf:
  pfcp:
    - addr: smf
      port: 8805
